- name: Deploy Apache Web Server
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Start Apache Service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes



